CREATE TABLE agencies
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	status    		INT NOT NULL DEFAULT 0,
	entity_num      INT NOT NULL DEFAULT 0,
	pay_type_id     INT NOT NULL DEFAULT 0,
	service_days    INT NOT NULL DEFAULT 0,
	agency_type_id  INT NOT NULL DEFAULT 0,
	client_type_id  INT NOT NULL DEFAULT 0,
	province  		INT NOT NULL DEFAULT 0,
	city      		INT NOT NULL DEFAULT 0,
	area      		INT NOT NULL DEFAULT 0,
	care_num  		INT NOT NULL DEFAULT 0,
	created_at		DATETIME NOT NULL DEFAULT 0,
	modified_at		DATETIME NOT NULL DEFAULT 0,
	addr      VARCHAR(255) NOT NULL DEFAULT '',
	contact   VARCHAR(255) NOT NULL DEFAULT '',
	mobile    VARCHAR(20)  NOT NULL DEFAULT '',
	email     VARCHAR(50)  NOT NULL DEFAULT '',
	remark    VARCHAR(255) NOT NULL DEFAULT '',
	weixin    VARCHAR(100) NOT NULL DEFAULT '',
	weixin_id VARCHAR(100) NOT NULL DEFAULT '',
	wx_appid  VARCHAR(100) NOT NULL DEFAULT '',
	wx_secret VARCHAR(100) NOT NULL DEFAULT '',
	wx_openid VARCHAR(100) NOT NULL DEFAULT '',
	viewname  VARCHAR(100) NOT NULL DEFAULT '' comment '公众号名称',
	realname  VARCHAR(100) NOT NULL DEFAULT '' comment '机构名称',
	username  VARCHAR(100) NOT NULL DEFAULT '',
	UNIQUE username(username)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE entities
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	agency_id INT NOT NULL DEFAULT 0,
	status    INT NOT NULL DEFAULT 0,
	province  INT NOT NULL DEFAULT 0,
	city      INT NOT NULL DEFAULT 0,
	area      INT NOT NULL DEFAULT 0,
	created_at  DATETIME NOT NULL DEFAULT 0,
	modified_at DATETIME NOT NULL DEFAULT 0,
	realname  VARCHAR(100) NOT NULL DEFAULT '' comment '机构名称',
	addr      VARCHAR(255) NOT NULL DEFAULT '',
	contact   VARCHAR(255) NOT NULL DEFAULT '',
	mobile    VARCHAR(20)  NOT NULL DEFAULT '',
	email     VARCHAR(50)  NOT NULL DEFAULT '',
	remark    VARCHAR(255) NOT NULL DEFAULT ''
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE agency_types
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name   VARCHAR(255) NOT NULL DEFAULT '',
	remark VARCHAR(255) NOT NULL DEFAULT ''
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE client_types
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name   VARCHAR(255) NOT NULL DEFAULT '',
	remark VARCHAR(255) NOT NULL DEFAULT ''
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE pay_types
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	pay    INT NOT NULL DEFAULT 0,
	name   VARCHAR(255) NOT NULL DEFAULT '',
	remark VARCHAR(255) NOT NULL DEFAULT ''
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE service_days
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name   VARCHAR(255) NOT NULL DEFAULT '',
	days   INT NOT NULL DEFAULT 0,
	remark VARCHAR(255) NOT NULL DEFAULT ''
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE schools
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	agency_id INT NOT NULL DEFAULT 0,
	status INT NOT NULL DEFAULT 0,
	name   VARCHAR(255) NOT NULL DEFAULT '',
	addr   VARCHAR(255) NOT NULL DEFAULT '',
	KEY agency_id(agency_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE grades
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	agency_id INT NOT NULL DEFAULT 0,
	status INT NOT NULL DEFAULT 0,
	name   VARCHAR(255) NOT NULL DEFAULT '',
	KEY agency_id(agency_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO agencies(entity_num,viewname,realname,username) VALUES(5,'弘翰教育', '弘翰文化教育机构','tester');
INSERT INTO users(agency_id,username,password) VALUES(1, 'admin', '7c4a8d09ca3762af61e59520943dc26494f8941b');
